import type { DailyActivity } from './activity.js'
import { renderActivity } from './daily-brief.js'

export const buildArchitectureWeeklyPrompt = (activity: DailyActivity): string =>
  [
    "Tu prépares la contribution d'un développeur au weekly des architectes.",
    `Voici les traces brutes de son activité du ${activity.window.label} : sessions Claude Code (ses demandes, les fichiers touchés) et activité GitHub.`,
    '',
    "Le public, ce sont des architectes : ils veulent savoir ce qui bouge dans le paysage technique, pas le détail du quotidien.",
    '',
    'Ne retiens que les gros sujets qui les concernent :',
    '- décisions et choix techniques : ADR, approche adoptée ou abandonnée, nouvelle convention',
    '- infrastructure et cloud : AWS, Terraform, files et bus de messages, stratégie de déploiement',
    '- intégrations entre services : contrats d\'API, SDK, événements, flux de données',
    '- CI/CD et outillage transverse : pipelines, actions partagées, monorepo, librairies communes',
    '- sécurité, gestion des secrets, observabilité (Sentry, logs, alerting)',
    '- dette technique, montées de version structurantes, remplacement d\'un outil',
    '- incidents de prod et leur cause racine',
    '',
    'Écarte tout le reste : corrections de bugs fonctionnels ou d\'interface, relectures de routine, mises à jour Dependabot sans impact, mises en prod courantes, tâches administratives, outillage personnel.',
    '',
    'Consignes :',
    "- Réponds en français, à la première personne (\"j'ai\", \"on a\"), prêt à être lu à l'oral.",
    "- Un résumé par projet. Un projet, c'est un dépôt : nomme-le sans l'organisation GitHub, et fusionne les traces Claude et GitHub qui le concernent.",
    "- Omets complètement un projet qui n'a aucun sujet d'architecture.",
    '- Au plus trois sujets par projet, les plus structurants en premier.',
    '- Une seule phrase courte par sujet, 20 mots maximum : la décision ou le changement, puis son état (mergé, en cours).',
    "- Pas de contexte, pas de cause, pas de liste de dépendances ou de fichiers : l'archi demandera s'il veut le détail.",
    '- Une même PR ne doit apparaître qu\'une fois.',
    '',
    'Format de sortie exact :',
    '## <projet>',
    '- **<sujet>** : une phrase (numéros de PR/issue entre parenthèses)',
    '## À discuter',
    "- une question par puce, en une phrase, uniquement si elle appelle un avis des archis ; omets la section si rien",
    '',
    'Exemple de ton attendu :',
    "- **Déploiements** : dev et preprod passent en série pour éviter les conflits de verrou Terraform, en review (#7307).",
    '',
    'Si aucun sujet ne passe le filtre, réponds uniquement : « Rien de structurant pour les archis sur la période. »',
    "N'invente rien : si une trace est ambiguë, reste factuel ou ignore-la.",
    '',
    '---',
    '',
    renderActivity(activity),
  ].join('\n')
